using System.Collections.Generic;
using NXOpen;
using NXOpen.Features;
using NXOpen.GeometricUtilities;
using NXOpen.UF;
using System;
using NXOpen.UserDefinedObjects;
using static TSG_Library.Extensions.Extensions;
using static NXOpen.UF.UFConstants;
using NXOpenUI;
using System.Globalization;
using NXOpen.Assemblies;
using System.Windows.Forms;
using TSG_Library.Utilities;
using NXOpen.Utilities;
using NXOpen.Preferences;
using TSG_Library.Properties;

namespace TSG_Library.UFuncs
{
    public partial class EditBlockForm
    {




        private static void NewMethod35()
        {
            TheUISession.NXMessageBox.Show("Caught exception", NXMessageBox.DialogType.Error,
                "Mirrored Component");
        }

        private static void NewMethod34()
        {
            TheUISession.NXMessageBox.Show("Caught exception", NXMessageBox.DialogType.Error,
                                "Not a block component");
        }

        private static void NewMethod33()
        {
            TheUISession.NXMessageBox.Show("Caught exception", NXMessageBox.DialogType.Error,
                                    "WorkPlane is null.  Reset Modeling State");
        }

        private static void NewMethod32()
        {
            TheUISession.NXMessageBox.Show("Caught exception", NXMessageBox.DialogType.Error,
                "WorkPlane is null.  Reset Modeling State");
        }

        private static void NewMethod24()
        {
            TheUISession.NXMessageBox.Show("Caught exception",
                NXMessageBox.DialogType.Error, "Invalid input");
        }

        private static void NewMethod23()
        {
            TheUISession.NXMessageBox.Show(
                                    "Caught exception",
                                    NXMessageBox.DialogType.Error,
                                    "Not a block component");
        }

        private static void NewMethod22()
        {
            TheUISession.NXMessageBox.Show(
                                    "Error",
                                    NXMessageBox.DialogType.Information,
                                    "This function is not allowed in this context");
        }

        private static void NewMethod25()
        {
            TheUISession.NXMessageBox.Show(
                                "Caught exception",
                                NXMessageBox.DialogType.Error,
                                "Not a block component");
        }

        private static void NewMethod27()
        {
            TheUISession.NXMessageBox.Show(
                                "Caught exception",
                                NXMessageBox.DialogType.Error,
                                "Not a block component");
        }

        private static void NewMethod26()
        {
            TheUISession.NXMessageBox.Show(
                                "Error",
                                NXMessageBox.DialogType.Information,
                                "This function is not allowed in this context");
        }


        private static void NewMethod28()
        {
            TheUISession.NXMessageBox.Show(
                "Caught exception",
                NXMessageBox.DialogType.Error,
                "Not a block component");
        }



        private static void NewMethod31()
        {
            TheUISession.NXMessageBox.Show("Caught exception : Match Block",
                NXMessageBox.DialogType.Error,
                "Can not match to the selected component");
        }

        private static void NewMethod30()
        {
            TheUISession.NXMessageBox.Show("Caught exception : Match Block",
                                NXMessageBox.DialogType.Error, "Mirrored Component");
        }

        private static void NewMethod29()
        {
            TheUISession.NXMessageBox.Show("Caught exception", NXMessageBox.DialogType.Error,
                                "Not a block component");
        }

        private static void NewMethod20()
        {
            TheUISession.NXMessageBox.Show("Caught exception : Match Block",
                NXMessageBox.DialogType.Information, "This function is not allowed in this context");
        }
        private static void NewMethod16()
        {
            TheUISession.NXMessageBox.Show("Caught exception", NXMessageBox.DialogType.Error,
                                "Not a block component");
        }

        private static void NewMethod15()
        {
            TheUISession.NXMessageBox.Show("Caught exception", NXMessageBox.DialogType.Error,
                "Mirrored Component");
        }

        private static void NewMethod18()
        {
            TheUISession.NXMessageBox.Show("Caught exception", NXMessageBox.DialogType.Error,
                                "Not a block component");
        }


        private static void NewMethod37()
        {
            TheUISession.NXMessageBox.Show("Caught exception", NXMessageBox.DialogType.Error,
                "Not a block component");
        }

        private static void NewMethod36()
        {
            TheUISession.NXMessageBox.Show("Caught exception", NXMessageBox.DialogType.Error,
                "Mirrored Component");
        }

    }
}
// 2045